feat: Начало работы над новым приложением ShearIt
AndreyMeltsov/java-shareit pull request #1
Opened 2023-04-17 01:35 UTC by AndreyMeltsov

2023-04-17 19:47 UTC, kalitva requested changes

2023-04-17 19:47 UTC, kalitva commented on pom.xml
> +			<artifactId>json-patch</artifactId>
А зачем это, точно нужна эта зависимость?

2023-04-17 19:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exceptions/ErrorHandler.java
> +    private static final String LOG_MESSAGE = "Bad request : ";
Особой необходимости выносить это сообщение в константу нет, константа обычно используется для значений, смысл которых неочевиден, с логированием же сообщения все понятно

2023-04-17 19:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @RequestBody Map<String, Object> fields) {
А почему используется хэшмап, а не `ItemDto`?

2023-04-17 19:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        return new Item(
Вместо конструкторов лучше используй `@Builder` ломбока

https://projectlombok.org/features/Builder

2023-04-17 19:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            Field field = ReflectionUtils.findField(Item.class, key);
Уф, там где можно обойтись без рефлекшена, лучше таки обойтись без него)

2023-04-17 19:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +                .anyMatch(x -> Objects.equals(x.getEmail(), user.getEmail()))) {
`x --> u`

2023-04-17 19:47 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +        Optional<User> oldUser = users.stream()
Не вижу смысла в том, чтобы выделять `oldUser` в переменную

2023-04-17 23:34 UTC, AndreyMeltsov commented on pom.xml
> +			<artifactId>json-patch</artifactId>
Я сначала сделал обработку PATCH запроса через json-patch, но потом когда дошел до тестов, увидел, что там обычный json и пришлось переделать. Забыл удалить.

2023-04-18 01:11 UTC, AndreyMeltsov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @RequestBody Map<String, Object> fields) {
Зато потренировался)

2023-04-18 21:46 UTC, kalitva approved these changes

2023-04-18 23:41 UTC, merged